defaults:
  - franka_rope_straighten_dp

agent:
  agent_name: pfc_equibot

model:
  hidden_dim: 4 # was 32
  encoder:
    backbone_type: ponita_fc
    backbone_args:
      num_ori: 6 # 8?


training:
  batch_size: 512 # 768?
